
package com.revature;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "StudyException", targetNamespace = "http://service.revature.com/")
public class StudyException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private StudyException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public StudyException_Exception(String message, StudyException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public StudyException_Exception(String message, StudyException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.revature.StudyException
     */
    public StudyException getFaultInfo() {
        return faultInfo;
    }

}
