
package com.revature;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudyServiceImplService", targetNamespace = "http://service.revature.com/", wsdlLocation = "http://localhost:8082/SOAPServiceDemo/study-session?wsdl")
public class StudyServiceImplService extends Service {

	private final static URL STUDYSERVICEIMPLSERVICE_WSDL_LOCATION;
	private final static WebServiceException STUDYSERVICEIMPLSERVICE_EXCEPTION;
	private final static QName STUDYSERVICEIMPLSERVICE_QNAME = new QName("http://service.revature.com/",
			"StudyServiceImplService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL("http://localhost:8082/SOAPServiceDemo/study-session?wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		STUDYSERVICEIMPLSERVICE_WSDL_LOCATION = url;
		STUDYSERVICEIMPLSERVICE_EXCEPTION = e;
	}

	public StudyServiceImplService() {
		super(__getWsdlLocation(), STUDYSERVICEIMPLSERVICE_QNAME);
	}

	public StudyServiceImplService(WebServiceFeature... features) {
		super(__getWsdlLocation(), STUDYSERVICEIMPLSERVICE_QNAME, features);
	}

	public StudyServiceImplService(URL wsdlLocation) {
		super(wsdlLocation, STUDYSERVICEIMPLSERVICE_QNAME);
	}

	public StudyServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, STUDYSERVICEIMPLSERVICE_QNAME, features);
	}

	public StudyServiceImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public StudyServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns StudyService
	 */
	@WebEndpoint(name = "StudyServiceImplPort")
	public StudyService getStudyServiceImplPort() {
		return super.getPort(new QName("http://service.revature.com/", "StudyServiceImplPort"), StudyService.class);
	}

	/**
	 * 
	 * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *                 on the proxy. Supported features not in the
	 *                 <code>features</code> parameter will have their default
	 *                 values.
	 * @return returns StudyService
	 */
	@WebEndpoint(name = "StudyServiceImplPort")
	public StudyService getStudyServiceImplPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://service.revature.com/", "StudyServiceImplPort"), StudyService.class,
				features);
	}

	private static URL __getWsdlLocation() {
		if (STUDYSERVICEIMPLSERVICE_EXCEPTION != null) {
			throw STUDYSERVICEIMPLSERVICE_EXCEPTION;
		}
		return STUDYSERVICEIMPLSERVICE_WSDL_LOCATION;
	}

}
