
package com.revature;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudyService", targetNamespace = "http://service.revature.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudyService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws StudyException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFlashcard", targetNamespace = "http://service.revature.com/", className = "com.revature.AddFlashcard")
    @ResponseWrapper(localName = "addFlashcardResponse", targetNamespace = "http://service.revature.com/", className = "com.revature.AddFlashcardResponse")
    public String addFlashcard(
        @WebParam(name = "arg0", targetNamespace = "")
        Flashcard arg0)
        throws StudyException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.revature.Flashcard>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllFlashcards", targetNamespace = "http://service.revature.com/", className = "com.revature.GetAllFlashcards")
    @ResponseWrapper(localName = "getAllFlashcardsResponse", targetNamespace = "http://service.revature.com/", className = "com.revature.GetAllFlashcardsResponse")
    public List<Flashcard> getAllFlashcards();

}
