INSERT INTO TOPIC VALUES(800, 'cats');
INSERT INTO TOPIC VALUES(835, 'coding');

INSERT INTO FLASHCARD (FLASHCARD_ID, QUESTION, ANSWER, TOPIC_ID) VALUES (999, 'What is Java?', 'A delicious beverage', 835);
INSERT INTO FLASHCARD (FLASHCARD_ID, QUESTION, ANSWER, TOPIC_ID) VALUES (1003, 'Do cats know Java?', 'NO', 800);
INSERT INTO FLASHCARD (FLASHCARD_ID, QUESTION, ANSWER, TOPIC_ID) VALUES (1998, 'What is Spring?', 'The season between winter and summer', 835);
INSERT INTO FLASHCARD (FLASHCARD_ID, QUESTION, ANSWER, TOPIC_ID) VALUES (777, 'Who is the best at coding?', 'Quackers the Duck', 835);
INSERT INTO FLASHCARD (FLASHCARD_ID, QUESTION, ANSWER, TOPIC_ID) VALUES (189, 'How old was the oldest known domestic cat?', '38 years', 800);

COMMIT;